### ISSUE TITLE
Problem with tsconfig.json, types

### ISSUE THREAD

**Issue by ArcanisCz** [bencbartlett/creep-tasks#2]
### Description of issue:
Hi, i have problems with types property in tsconfig.json while compiling, it throws error.
```
    "types": [
      "lodash",
      "typed-screeps"
    ]
```
If i remove theese lines, typings works just fine (using Intellij idea) and project compiles successfully.
They are also correctly installed in node_modules
(for the record, same problem with Overmind)

### Steps to reproduce:

- npm install
- screeps.config.json (same as for Overmind)
- npm run push-pserver

### Error message:
```
rpt2: options error TS2688 Cannot find type definition file for 'typed-screeps'.
[!] (rpt2 plugin) Error: D:/git/creep-tasks/src/creep-tasks/prototypes.ts(6,23): semantic error TS2693 'Creep' only refers to a type, but is being used as a value here.


```

### Other information:
- `creep-tasks` version: 1.0.0
    - Commit hash: 5dce5e30dba9e750f4e5f63944fa1a27204a8c79
- Using `creep-tasks` with: {TypeScript} 
- Issue is with dependency: {Yes}

**Comment by bencbartlett** [comment]
I'll change this in the tsconfig.json soon. I'm repackaging this as a typed npm module, which hopefully should resolve some of the cyclic import errors in #2.
