### ISSUE TITLE
Getting the package using npm does not work

### ISSUE THREAD

**Issue by tiniuclx** [bencbartlett/creep-tasks#4]
### Description of issue:
I installed the package as described in README.md (by navigating into the root folder of my AI and running `npm install creep-tasks`). Afterwards, I `require`'d it in my scripts but Screeps said it could not find the module named `creep-tasks`. 

Looking at the files installed by npm, only the type definitions were installed. The error might come from [this line](https://github.com/bencbartlett/creep-tasks/blob/7c49da6a26642602be25b2aa9a998739c9cc4a0b/package.json#L37) inside package.json , though I am not at all familiar with npm. I believe `"files"` within package.json should contain `"src/**/*"` as opposed to `"dist/**/*"`.

### Steps to reproduce:

`npm install creep-tasks`
Try to run AI using `creep-tasks`
Failure!

### Error message:

```
Error: Unknown module 'creep-tasks'
    at Object.requireFn (<runtime>:30185:23)
    at role.patroller:1:49
    at role.patroller:15:3
    at Object.exports.evalCode (<runtime>:15727:76)
    at Object.requireFn (<runtime>:30203:28)
    at main:8:21
    at main:184:3
    at Object.exports.evalCode (<runtime>:15727:76)
    at Object.requireFn (<runtime>:30203:28)
```

### Other information:
- `creep-tasks` version: 1.2.0 {You can find this in package.json}
    - Commit hash: 7c49da6a26642602be25b2aa9a998739c9cc4a0b {Please include the specific commit hash if known}
- Using `creep-tasks` with: JavaScript
- Issue is with dependency: No

**Comment by bencbartlett** [comment]
`npm install` only works if you have your Screeps codebase set up with NPM with a `package.json` and deploy to servers using some sort of bundler like rollup or webpack. See [`screeps-typescript-starter`](https://github.com/screepers/screeps-typescript-starter) for an example setup. If you don't have this, just copy-paste the [compiled output file](https://github.com/bencbartlett/creep-tasks/blob/master/bin/creep-tasks.js) to a new module in Screeps called `creep-tasks.js`.

**Comment by tiniuclx** [comment]
Ah, that explains it. I was not managing screens using mom as you predicted. Thanks for the explanation, it will certainly be useful!
